# Generated by Django 5.0.4 on 2024-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("telegram_id", models.CharField(max_length=100, unique=True)),
                ("step", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(help_text="Enter the product link")),
                (
                    "size",
                    models.CharField(help_text="Enter the product size", max_length=50),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Enter the product color", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter the product description"),
                ),
            ],
        ),
    ]
