# Generated by Django 5.0.4 on 2024-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='step',
            field=models.CharField(choices=[('H', 'Home'), ('N', 'New Order'), ('M', 'My  Orders')], default='H', max_length=1),
        ),
    ]
