# Generated by Django 5.0.4 on 2024-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('N', 'New Order'), ('M', 'My  Orders')], default='P', max_length=1),
        ),
    ]
