# Generated by Django 5.0.4 on 2024-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_wallet_options_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], default='D', max_length=1)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected')], default='P', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
