# Generated by Django 5.0.4 on 2024-05-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_transaction_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
