# Generated by Django 5.0.4 on 2024-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_transaction_options_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'وضعیت سفارش'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the product description', null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار'), ('A', 'تایید شده'), ('C', 'پرداخت شده'), ('F', 'لغو شده'), ('S', 'ارسال شده'), ('R', 'دریافت شده')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], default='W', max_length=1),
        ),
    ]
