# Generated by Django 5.0.4 on 2024-05-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderstatus_options_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'واریز پول'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected')], default='P', max_length=1)),
                ('description', models.TextField(blank=True, help_text='Enter the product description', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
            options={
                'verbose_name_plural': 'صورت حساب ها',
            },
        ),
    ]
