# Generated by Django 4.2.16 on 2025-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_product_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='derscription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='آدرس تصویر'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(help_text='Enter the product link', max_length=1000, verbose_name='لینک'),
        ),
    ]
