# Generated by Django 4.2.16 on 2025-08-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='ASIN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='customization_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='گزینه\u200cهای سفارشی'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='feature_bullets',
            field=models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='تصاویر'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت قبل از تخفیف'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
