# Generated by Django 4.2.16 on 2025-08-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_product_link_remove_productdetails_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='availability',
        ),
    ]
