# Generated by Django 4.2.16 on 2025-09-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_store_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'فروشگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'verbose_name_plural': 'محصولات فروشگاه ها'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='store_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storeproduct'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'store_product')},
        ),
    ]
