version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "until python manage.py migrate; do
                 echo 'Waiting for database...'; sleep 2;
               done &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://root:RPY0mHYecwe7imLXRjE7MWfM@monte-rosa.liara.cloud:33759/postgres

  bot:
    build: .
    command: bash -c "while true; do python bot.py; sleep 1; done"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://root:RPY0mHYecwe7imLXRjE7MWfM@monte-rosa.liara.cloud:33759/postgres
